### ISSUE TITLE
400 origin_mismatch error when installing

### ISSUE THREAD

**Issue by DannyBen** [socrateslee/mdreader#1]
I am getting an error when trying to install.

Error: origin_mismatch
Application: mdReader

Tried both a regular google account and an apps account (which I hope it can also support).

**Comment by socratescli** [comment]
Seems the old host address is unavailable, I have transfer the host to http://socrateslee.github.io/mdreader/.

**Comment by DannyBen** [comment]
I was able to install it using the above link, and I see it appears in the "Account Permissions" page, but still opening .md with it, it launches the authentication window again, followed by the error.

Is it a problem on my side, or do you need to do something else for it to work?

**Comment by socratescli** [comment]
It seems change application id and manifest.json won't work, I don't know if Google Drive would somehow cache the application address.

**Comment by socratescli** [comment]
change the API of Google Drive, "Drive UI Integration"->"Open Url" in console.developers.google.com, seems working
